# This file is part of facho.  The COPYRIGHT file at the top level of
# this repository contains the full copyright notices and license terms.

"""
Constructores de documentos XML UBL 2.1 para DIAN Colombia.
"""

# Builders principales
from .invoice_builder import (
    InvoiceBuilder,
    InvoiceConfig,
    InvoiceData,
    InvoiceLine,
    Party,
    Address,
)
from .credit_note_builder import CreditNoteBuilder, CreditNoteData
from .debit_note_builder import DebitNoteBuilder, DebitNoteData

# Builders adicionales
from .support_document_builder import SupportDocumentBuilder, SupportDocumentData
from .export_invoice_builder import (
    ExportInvoiceBuilder,
    ExportInvoiceData,
    DeliveryTerms,
    DeliveryInfo,
    ExchangeRate,
)
from .contingency_invoice_builder import (
    ContingencyInvoiceBuilder,
    ContingencyInvoiceData,
)
from .pos_document_builder import PosDocumentBuilder, PosDocumentData

# CUFE/CUDE/CUDS Calculator
from .cufe import (
    CufeInput,
    calculate_cufe,
    calculate_cude,
    calculate_cuds,
    calculate_software_security_code,
    calculate_cufe_from_taxes,
    calculate_cude_from_taxes,
    verify_cufe,
    verify_cude,
    get_uuid_type,
    calculate_uuid_by_doc_type,
    format_amount,
    build_cufe_string,
)

# SOAP WS-Security utilities
from .soap_client import (
    build_wssec_soap,
    get_endpoint,
    SOAP_ACTIONS,
    build_send_test_set_body,
    build_send_bill_sync_body,
    build_send_bill_async_body,
    build_get_status_body,
    build_get_status_zip_body,
)

# AllowanceCharge (descuentos y cargos)
from .allowance_charge import (
    AllowanceCharge,
    add_allowance_charges_to_element,
    calculate_totals,
    create_discount,
    create_charge,
    ALLOWANCE_REASON_CODES,
    CHARGE_REASON_CODES,
)

# Sistema de impuestos
from .taxes import (
    Tax,
    TaxTotal,
    TAX_CODES as TAX_CODES_FULL,
    TAX_NAMES,
    WITHHOLDING_TAX_CODES,
    IVA_RATES,
    RETENTION_RATES,
    truncar,
    truncar_decimal,
    formato_dinero,
    agrupar_impuestos,
    separar_impuestos_retenciones,
    calcular_totales_impuestos,
)

# Sistema de excepciones
from .exceptions import (
    FachoError,
    ValidationError,
    ConfigurationError,
    SignatureError,
    CertificateError,
    CertificateExpiredError,
    CertificateRevokedError,
    DianError,
    DuplicateInvoiceError,
    XmlBuildError,
    CufeError,
    CufeValidationError,
    RangeError,
    ResolutionExpiredError,
    ResolutionNotFoundError,
    ReferenceNotFoundError,
    TotalsValidationError,
    UvtLimitExceededError,
    NetworkError,
    FachoTimeoutError,
    DIAN_ERROR_CODES,
    get_dian_error_description,
    parse_dian_errors,
    create_dian_exception,
)

# Validadores
from .validators import (
    InvoiceValidator,
    ConfigValidator,
    PartyValidator,
    InvoiceLineValidator,
    ProductionValidator,
    validate_invoice,
    validate_before_build,
    validate_nit,
    validate_date,
    validate_time,
    validate_uuid,
    validate_not_empty,
    validate_positive_number,
    validate_resolution_dates,
    validate_cufe_format,
    validate_consecutive_in_range,
    validate_totals,
    validate_credit_note_reference,
    validate_debit_note_reference,
    validate_export_invoice,
    validate_pos_limits,
    calculate_remaining_in_range,
    is_resolution_expiring_soon,
)

# Constantes
from .constants import (
    NS,
    NS_SOAP,
    SCHEME_AGENCY_ATTRS,
    DIAN_PROFILE_ID,
    DIAN_PROFILE_ID_CREDIT_NOTE,
    DIAN_PROFILE_ID_DEBIT_NOTE,
    DIAN_PROFILE_ID_EXPORT,
    DIAN_PROFILE_ID_CONTINGENCY,
    DIAN_PROFILE_ID_SUPPORT,
    DIAN_UBL_VERSION,
    DIAN_CUSTOMIZATION_ID,
    INVOICE_TYPE_CODE,
    CREDIT_NOTE_TYPE_CODE,
    DEBIT_NOTE_TYPE_CODE,
    EXPORT_INVOICE_TYPE_CODE,
    POS_INVOICE_TYPE_CODE,
    CONTINGENCY_INVOICE_TYPE_CODE,
    SUPPORT_DOCUMENT_TYPE_CODE,
    TAX_CODES,
    CREDIT_REASONS,
    DEBIT_REASONS,
    DOC_TYPES,
    DOC_TYPES_FULL,
    COUNTRY_ID_ATTRS,
    AUTHORIZATION_PROVIDER_ID,
    INCOTERMS,
    CURRENCIES,
    DIAN_ENDPOINTS,
    GENERIC_CONSUMER,
    UVT_VALUES,
    TAX_REGIMES,
    ID_TYPES,
    CREDIT_NOTE_RESPONSE_CODES,
    DEBIT_NOTE_RESPONSE_CODES,
    # Algoritmos de firma
    C14N_ALG,
    C14N_EXC_ALG,
    ENVELOPED_SIG,
    RSA_SHA256,
    SHA256_ALG,
    SIGNED_PROPS_TYPE,
    POLITICA_URL,
    POLITICA_HASH,
)

__all__ = [
    # Builders
    'InvoiceBuilder',
    'CreditNoteBuilder',
    'DebitNoteBuilder',
    'SupportDocumentBuilder',
    'ExportInvoiceBuilder',
    'ContingencyInvoiceBuilder',
    'PosDocumentBuilder',
    # Data classes
    'InvoiceConfig',
    'InvoiceData',
    'InvoiceLine',
    'Party',
    'Address',
    'CreditNoteData',
    'DebitNoteData',
    'SupportDocumentData',
    'ExportInvoiceData',
    'ContingencyInvoiceData',
    'PosDocumentData',
    'DeliveryTerms',
    'DeliveryInfo',
    'ExchangeRate',
    'AllowanceCharge',
    # CUFE/CUDE/CUDS
    'CufeInput',
    'calculate_cufe',
    'calculate_cude',
    'calculate_cuds',
    'calculate_software_security_code',
    'calculate_cufe_from_taxes',
    'calculate_cude_from_taxes',
    'verify_cufe',
    'verify_cude',
    'get_uuid_type',
    'calculate_uuid_by_doc_type',
    'format_amount',
    'build_cufe_string',
    # SOAP WS-Security
    'build_wssec_soap',
    'get_endpoint',
    'SOAP_ACTIONS',
    'build_send_test_set_body',
    'build_send_bill_sync_body',
    'build_send_bill_async_body',
    'build_get_status_body',
    'build_get_status_zip_body',
    # Tax classes and functions
    'Tax',
    'TaxTotal',
    'truncar',
    'truncar_decimal',
    'formato_dinero',
    'agrupar_impuestos',
    'separar_impuestos_retenciones',
    'calcular_totales_impuestos',
    # AllowanceCharge functions
    'add_allowance_charges_to_element',
    'calculate_totals',
    'create_discount',
    'create_charge',
    # Exceptions
    'FachoError',
    'ValidationError',
    'ConfigurationError',
    'SignatureError',
    'CertificateError',
    'CertificateExpiredError',
    'CertificateRevokedError',
    'DianError',
    'DuplicateInvoiceError',
    'XmlBuildError',
    'CufeError',
    'CufeValidationError',
    'RangeError',
    'ResolutionExpiredError',
    'ResolutionNotFoundError',
    'ReferenceNotFoundError',
    'TotalsValidationError',
    'UvtLimitExceededError',
    'NetworkError',
    'FachoTimeoutError',
    'DIAN_ERROR_CODES',
    'get_dian_error_description',
    'parse_dian_errors',
    'create_dian_exception',
    # Validators
    'InvoiceValidator',
    'ConfigValidator',
    'PartyValidator',
    'InvoiceLineValidator',
    'ProductionValidator',
    'validate_invoice',
    'validate_before_build',
    'validate_nit',
    'validate_date',
    'validate_time',
    'validate_uuid',
    'validate_not_empty',
    'validate_positive_number',
    'validate_resolution_dates',
    'validate_cufe_format',
    'validate_consecutive_in_range',
    'validate_totals',
    'validate_credit_note_reference',
    'validate_debit_note_reference',
    'validate_export_invoice',
    'validate_pos_limits',
    'calculate_remaining_in_range',
    'is_resolution_expiring_soon',
    # Constants
    'NS',
    'NS_SOAP',
    'SCHEME_AGENCY_ATTRS',
    'DIAN_PROFILE_ID',
    'DIAN_PROFILE_ID_CREDIT_NOTE',
    'DIAN_PROFILE_ID_DEBIT_NOTE',
    'DIAN_PROFILE_ID_EXPORT',
    'DIAN_PROFILE_ID_CONTINGENCY',
    'DIAN_PROFILE_ID_SUPPORT',
    'DIAN_UBL_VERSION',
    'DIAN_CUSTOMIZATION_ID',
    'INVOICE_TYPE_CODE',
    'CREDIT_NOTE_TYPE_CODE',
    'DEBIT_NOTE_TYPE_CODE',
    'EXPORT_INVOICE_TYPE_CODE',
    'POS_INVOICE_TYPE_CODE',
    'CONTINGENCY_INVOICE_TYPE_CODE',
    'SUPPORT_DOCUMENT_TYPE_CODE',
    'TAX_CODES',
    'TAX_CODES_FULL',
    'TAX_NAMES',
    'WITHHOLDING_TAX_CODES',
    'IVA_RATES',
    'RETENTION_RATES',
    'CREDIT_REASONS',
    'DEBIT_REASONS',
    'DOC_TYPES',
    'DOC_TYPES_FULL',
    'COUNTRY_ID_ATTRS',
    'AUTHORIZATION_PROVIDER_ID',
    'INCOTERMS',
    'CURRENCIES',
    'DIAN_ENDPOINTS',
    'GENERIC_CONSUMER',
    'UVT_VALUES',
    'TAX_REGIMES',
    'ID_TYPES',
    'CREDIT_NOTE_RESPONSE_CODES',
    'DEBIT_NOTE_RESPONSE_CODES',
    'ALLOWANCE_REASON_CODES',
    'CHARGE_REASON_CODES',
    # Algoritmos de firma
    'C14N_ALG',
    'C14N_EXC_ALG',
    'ENVELOPED_SIG',
    'RSA_SHA256',
    'SHA256_ALG',
    'SIGNED_PROPS_TYPE',
    'POLITICA_URL',
    'POLITICA_HASH',
]
